# timeOut degerini değiştirmeyin
browser=chrome
instuLearn=https://qa.instulearn.com/
name=yourTestName
password=yourPassword
studentMail=yourStudentMail
teacherMail=yourTeacherMail
timeout=10
url=https://qa.instulearn.com/
userName=ahmet
